# -*- coding: utf-8 -*-
"""Fake_News_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KYptjQmV4HiFoERmKTuSTCjgl9fuf3IX
"""

!pip install numpy pandas sklearn

"""# Make necessary imports:"""

import numpy as np
import pandas as pd
import itertools
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

"""#  read the data into a DataFrame"""

#Read the data
df=pd.read_csv('news.csv')
#Get shape and head
df.shape
df.head()

"""# labels from the DataFrame."""

#DataFlair - Get the labels
labels=df.label
labels.head()

"""# Split the dataset into training and testing sets."""

x_train,x_test,y_train,y_test=train_test_split(df['text'], labels, test_size=0.2, random_state=7)

"""# fit and transform the vectorizer on the train set, and transform the vectorizer on the test set."""

#DataFlair - Initialize a TfidfVectorizer
tfidf_vectorizer=TfidfVectorizer(stop_words='english', max_df=0.7)
#DataFlair - Fit and transform train set, transform test set
tfidf_train=tfidf_vectorizer.fit_transform(x_train) 
tfidf_test=tfidf_vectorizer.transform(x_test)

"""# initialize a PassiveAggressiveClassifier"""

pac=PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train,y_train)
#DataFlair - Predict on the test set and calculate accuracy
y_pred=pac.predict(tfidf_test)
score=accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

"""# confusion matrix"""

confusion_matrix(y_test,y_pred, labels=['FAKE','REAL'])